"""
strategies/base_strategy.py — Abstract Base Strategy
══════════════════════════════════════════════════════
Every strategy MUST inherit from BaseStrategy and implement
the generate_signal() method. The strategy engine loads strategies
dynamically from the strategies/ folder — any .py file that contains
a class inheriting BaseStrategy is automatically available in the
dashboard dropdown.

To create a new strategy:
  1. Create a new file in strategies/  e.g. strategies/vwap_reversal.py
  2. Create a class inheriting BaseStrategy
  3. Set name, description, instruments
  4. Implement generate_signal()
  5. That's it — the dashboard will auto-detect it

Signal return format:
  {
    "action":     "CALL" | "PUT" | "NONE",
    "confidence": 0-100,        # how confident the signal is
    "conditions_met": 3,        # out of 5
    "conditions_detail": [...], # list of condition descriptions
    "entry_type": "breakout" | "pullback",
    "reason":     "...",        # human readable reason
    "symbol":     "NIFTY",
    "timeframe":  15,
  }
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Optional
import pandas as pd


@dataclass
class Signal:
    """Represents a trade signal generated by a strategy."""

    # Core signal
    action          : str   = "NONE"   # "CALL", "PUT", or "NONE"
    symbol          : str   = ""
    timeframe       : int   = 15

    # Confidence & scoring
    confidence      : int   = 0        # 0-100
    conditions_met  : int   = 0        # how many conditions triggered
    conditions_total: int   = 5        # total conditions checked
    conditions_detail: list = field(default_factory=list)  # per-condition descriptions

    # Entry detail
    entry_type      : str   = ""       # "breakout" or "pullback"
    suggested_strike: str   = ""       # e.g. "22200CE" or "48000PE"
    reason          : str   = ""       # human-readable summary

    # Market context at signal time
    bias_score      : int   = 0        # market intel bias score
    opening_range_high: float = 0.0
    opening_range_low : float = 0.0
    current_price   : float = 0.0

    def is_tradeable(self) -> bool:
        """Returns True if this signal should be acted upon."""
        return self.action in ("CALL", "PUT")

    def to_dict(self) -> dict:
        return {
            "action":            self.action,
            "symbol":            self.symbol,
            "timeframe":         self.timeframe,
            "confidence":        self.confidence,
            "conditions_met":    self.conditions_met,
            "conditions_total":  self.conditions_total,
            "conditions_detail": self.conditions_detail,
            "entry_type":        self.entry_type,
            "suggested_strike":  self.suggested_strike,
            "reason":            self.reason,
            "bias_score":        self.bias_score,
            "opening_range_high": self.opening_range_high,
            "opening_range_low":  self.opening_range_low,
            "current_price":     self.current_price,
        }

    def __repr__(self):
        if not self.is_tradeable():
            return f"Signal(NONE — {self.reason})"
        return (
            f"Signal({self.action} {self.symbol} | "
            f"Confidence:{self.confidence}% | "
            f"Conditions:{self.conditions_met}/{self.conditions_total} | "
            f"{self.reason})"
        )


# No-trade signal factory
SIGNAL_NONE = lambda reason="": Signal(action="NONE", reason=reason)


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    Inherit this and implement generate_signal().
    """

    # ── Strategy metadata (set these in your subclass) ────────────────────────
    name        : str  = "Base Strategy"
    description : str  = "Abstract base — do not use directly"
    instruments : list = ["NIFTY", "BANKNIFTY"]
    option_type : str  = "BUY"    # "BUY" or "SELL"
    version     : str  = "1.0"

    # Minimum completed candles needed before signal can be generated
    min_candles_15m : int = 3
    min_candles_5m  : int = 5

    def __init__(self, config: dict):
        """
        Args:
            config : Settings dict from database/dashboard
                     (sl_percentage, risk_reward_ratio,
                      min_signal_conditions, etc.)
        """
        self.config = config

    @abstractmethod
    def generate_signal(
        self,
        symbol      : str,
        candles_15m : pd.DataFrame,
        candles_5m  : pd.DataFrame,
        opening_range: Optional[dict],
        market_bias : int = 0,
    ) -> Signal:
        """
        Core method — analyse candles and return a Signal.

        Args:
            symbol       : "NIFTY" or "BANKNIFTY"
            candles_15m  : DataFrame of completed 15-min candles
                           Index: open_time, Cols: open,high,low,close,volume
            candles_5m   : DataFrame of completed 5-min candles
            opening_range: {"high":x, "low":y, "open":z} or None
            market_bias  : -10 to +10 from MarketIntel engine

        Returns:
            Signal object with action CALL, PUT, or NONE
        """
        pass

    def can_generate_signal(
        self,
        candles_15m: pd.DataFrame,
        candles_5m : pd.DataFrame,
        opening_range: Optional[dict],
    ) -> tuple[bool, str]:
        """
        Pre-check before calling generate_signal().
        Returns (can_generate: bool, reason: str).
        """
        if opening_range is None:
            return False, "Opening range not yet established (need first 15-min candle)"

        if len(candles_15m) < self.min_candles_15m:
            return False, (
                f"Not enough 15-min candles "
                f"({len(candles_15m)}/{self.min_candles_15m})"
            )

        if len(candles_5m) < self.min_candles_5m:
            return False, (
                f"Not enough 5-min candles "
                f"({len(candles_5m)}/{self.min_candles_5m})"
            )

        return True, "OK"

    def __repr__(self):
        return f"{self.__class__.__name__}(v{self.version})"
